package be.drakarah.intonation.data

import kotlinx.serialization.Serializable

/** On-disk backup format. Dedicated DTOs — deliberately NOT the `@Entity` classes — so a future
 * DB migration can't silently change the file format. Autogenerated ids are omitted; import
 * re-keys foreign keys. `daily_stats` is not stored (it's derived; rebuilt on import). */
const val BACKUP_FORMAT = "intonation-trainer-backup"
const val BACKUP_VERSION = 1

@Serializable
data class BackupEnvelope(
    val format: String,
    val backupVersion: Int,
    val dbSchemaVersion: Int,
    val appVersionCode: Int,
    val exportedAt: Long,
    val data: BackupData,
)

@Serializable
data class BackupData(
    val sessions: List<BackupSession>,
    val personalBests: List<BackupPersonalBest>,
    val achievements: List<BackupAchievement>,
)

/** A session with its attempts nested, so import can re-key the foreign key in one pass. */
@Serializable
data class BackupSession(
    val startedAt: Long,
    val endedAt: Long?,
    val exerciseType: String,
    val mode: String,
    val configKey: String,
    val totalScore: Int,
    val maxScore: Int,
    val avgAbsCents: Float?,
    val completed: Boolean,
    val epochDay: Int?,
    val contextJson: String?,
    val attempts: List<BackupAttempt>,
)

@Serializable
data class BackupAttempt(
    val promptIndex: Int,
    val timestamp: Long,
    val exerciseType: String,
    val targetMidi: Int,
    val targetFreqHz: Float,
    val startMidi: Int?,
    val stringMidi: Int?,
    val positionId: String?,
    val playedFreqHz: Float?,
    val centsError: Float?,
    val reactionTimeMs: Long?,
    val timeToStableMs: Long?,
    val score: Int,
    val stars: Int,
    val quality: String,
    val epochDay: Int?,
    val outcome: String?,
    val energyLevel: Float?,
    val retryCount: Int?,
    val sustainHeldMs: Long?,
    val sustainResets: Int?,
    val steadinessCents: Float?,
    val captureWobbleCents: Float?,
    val extrasJson: String?,
)

@Serializable
data class BackupPersonalBest(
    val configKey: String,
    val score: Int,
    val maxScore: Int,
    val achievedAt: Long,
)

@Serializable
data class BackupAchievement(
    val achievementId: String,
    val unlockedAt: Long,
)

// --- Entity ↔ DTO mapping (the single boundary between storage and file format) ---

internal fun SessionEntity.toBackup(attempts: List<AttemptEntity>) = BackupSession(
    startedAt = startedAt, endedAt = endedAt, exerciseType = exerciseType, mode = mode,
    configKey = configKey, totalScore = totalScore, maxScore = maxScore, avgAbsCents = avgAbsCents,
    completed = completed, epochDay = epochDay, contextJson = contextJson,
    attempts = attempts.map { it.toBackup() },
)

internal fun BackupSession.toEntity() = SessionEntity(
    startedAt = startedAt, endedAt = endedAt, exerciseType = exerciseType, mode = mode,
    configKey = configKey, totalScore = totalScore, maxScore = maxScore, avgAbsCents = avgAbsCents,
    completed = completed, epochDay = epochDay, contextJson = contextJson,
)

internal fun AttemptEntity.toBackup() = BackupAttempt(
    promptIndex = promptIndex, timestamp = timestamp, exerciseType = exerciseType,
    targetMidi = targetMidi, targetFreqHz = targetFreqHz, startMidi = startMidi,
    stringMidi = stringMidi, positionId = positionId, playedFreqHz = playedFreqHz,
    centsError = centsError, reactionTimeMs = reactionTimeMs, timeToStableMs = timeToStableMs,
    score = score, stars = stars, quality = quality, epochDay = epochDay, outcome = outcome,
    energyLevel = energyLevel, retryCount = retryCount, sustainHeldMs = sustainHeldMs,
    sustainResets = sustainResets, steadinessCents = steadinessCents,
    captureWobbleCents = captureWobbleCents, extrasJson = extrasJson,
)

internal fun BackupAttempt.toEntity(sessionId: Long) = AttemptEntity(
    sessionId = sessionId, promptIndex = promptIndex, timestamp = timestamp,
    exerciseType = exerciseType, targetMidi = targetMidi, targetFreqHz = targetFreqHz,
    startMidi = startMidi, stringMidi = stringMidi, positionId = positionId,
    playedFreqHz = playedFreqHz, centsError = centsError, reactionTimeMs = reactionTimeMs,
    timeToStableMs = timeToStableMs, score = score, stars = stars, quality = quality,
    epochDay = epochDay, outcome = outcome, energyLevel = energyLevel, retryCount = retryCount,
    sustainHeldMs = sustainHeldMs, sustainResets = sustainResets, steadinessCents = steadinessCents,
    captureWobbleCents = captureWobbleCents, extrasJson = extrasJson,
)
