package be.drakarah.intonation.dsp.detection

import kotlin.math.abs
import kotlin.math.ln
import kotlin.math.pow
import kotlin.math.sqrt

/** SHELVED RESEARCH — a per-rig template octave-verifier that was explored as "rule 3" for
 * [be.drakarah.intonation.dsp.PitchGate] and did NOT pan out. Lives in the test source set (never
 * shipped), exercised only by the guarded eval `TemplateDecompositionSpike`. Kept as a documented
 * dead-end, like the acf2x write-up in DETECTION.md §12.6. See docs/second-pipeline-plan.md §8/§11.
 *
 * The idea: the double bass's #1 detection failure is the octave-up read on low pizz notes (a fingered
 * note plus a sympathetically ringing open string — polyphony forced through a monophonic estimator).
 * A template DECOMPOSITION over measured per-rig combs promised to separate a *true* octave-up from a
 * *genuine* mid note by explaining the ringing open string as its own source.
 *
 * Why it failed (measured on the 2026-07-22 chromatic corpus, all three metrics + sparse/dense
 * dictionaries + finer FFT + threshold sweeps): a genuine note whose sub-octave is a hard-ringing open
 * string (Mi2/open-E, La2/open-A) is **spectrally identical** to a true octave-up — the open string
 * really is sounding an octave down. A genuine La2 voted "sub-octave" 63%, *higher* than the actual
 * Fa1→F2 octave-up at 48%, so no threshold halves the octave-ups without also halving genuine notes.
 * The only signal that separates them is the *prompted note* (context), which the target-aware layer
 * (`ignoreWrongOctave` / octave-fold) already exploits. A target-agnostic per-window discriminator
 * cannot do it. DETECTION.md §12.6 has the full write-up.
 */

/** A per-rig dictionary of MEASURED harmonic templates — one magnitude spectrum per calibration
 * anchor note, on the detector's FFT grid. A template for any pitch is generated by frequency-shifting
 * the nearest anchor (its whole comb moves with the ratio), so the roll-off the mic imposes is carried
 * in the measured shape rather than assumed. */
class HarmonicTemplateDictionary internal constructor(
    /** FFT bin resolution the templates were measured at (Hz); templates shift on this grid. */
    val df: Float,
    private val anchorHz: FloatArray,             // ascending
    private val anchorSpectra: Array<FloatArray>, // each L2-normalised, length == nBins
) {
    val nBins: Int get() = if (anchorSpectra.isEmpty()) 0 else anchorSpectra[0].size

    init {
        require(anchorHz.size == anchorSpectra.size && anchorHz.isNotEmpty()) { "dictionary size mismatch" }
    }

    /** The comb for a note at [fHz] on the [nBins]-bin grid: take the nearest anchor (in log-frequency)
     * and shift its measured spectrum by the pitch ratio, then L2-normalise. [df]/[nBins] must match
     * the grid the dictionary was measured at (the product's standard 44100/4096 ≈ 10.77 Hz). */
    fun templateColumn(fHz: Float, df: Float, nBins: Int): FloatArray {
        var best = 0; var bestD = Float.MAX_VALUE
        for (i in anchorHz.indices) {
            val d = abs(ln(fHz.toDouble()) - ln(anchorHz[i].toDouble())).toFloat()
            if (d < bestD) { bestD = d; best = i }
        }
        val src = anchorSpectra[best]
        val ratio = fHz / anchorHz[best]
        // Shift UP by ratio: the partial at src bin i lands at out bin i·ratio → out[b] samples src[b/ratio].
        val out = FloatArray(nBins) { b ->
            val srcBin = b / ratio
            val i = srcBin.toInt()
            if (i < 0 || i + 1 >= src.size) 0f
            else { val fr = srcBin - i; src[i] * (1f - fr) + src[i + 1] * fr }
        }
        return l2normalize(out)
    }

    companion object {
        /** Cap the comb: above ~1 kHz partials are weak and bins get sparse; also bounds the NNLS. */
        const val MAX_TEMPLATE_HZ = 1000f
        /** Half-window (bins) searched around a partial's nominal bin when measuring — tolerates
         * slight inharmonicity of the low strings. */
        private const val PARTIAL_SEARCH_BINS = 2

        /** One calibration take reduced to its magnitude spectrum (already median-averaged over the
         * sustained middle of the take by the caller) plus the pitch that was played. */
        class Anchor(val fundamentalHz: Float, val magnitudeSpectrum: FloatArray, val df: Float)

        /** Builds the dictionary from the calibration anchors. Each anchor's spectrum is cleaned to its
         * harmonic comb (energy only at k·f ± a couple bins — drops broadband noise between partials so
         * the shifted template matches structure, not room hiss) and L2-normalised. Returns null when
         * there are too few usable anchors. */
        fun build(anchors: List<Anchor>): HarmonicTemplateDictionary? {
            if (anchors.size < 3) return null
            val df = anchors.first().df
            val nBins = (MAX_TEMPLATE_HZ / df).toInt().coerceAtMost(anchors.first().magnitudeSpectrum.size)
            val usable = anchors.filter { it.magnitudeSpectrum.size >= nBins && it.fundamentalHz > 0f }
                .sortedBy { it.fundamentalHz }
            if (usable.size < 3) return null
            val hz = FloatArray(usable.size) { usable[it].fundamentalHz }
            val spectra = Array(usable.size) { combOf(usable[it], nBins) }
            if (spectra.any { s -> s.all { it == 0f } }) return null
            return HarmonicTemplateDictionary(df, hz, spectra)
        }

        /** Keep only harmonic-peak energy of [a] up to [nBins]: for each harmonic k, the peak within
         * ±[PARTIAL_SEARCH_BINS] of k·f. L2-normalised. */
        private fun combOf(a: Anchor, nBins: Int): FloatArray {
            val comb = FloatArray(nBins)
            var k = 1
            while (k * a.fundamentalHz < MAX_TEMPLATE_HZ) {
                val center = (k * a.fundamentalHz / a.df).toInt()
                val lo = (center - PARTIAL_SEARCH_BINS).coerceAtLeast(0)
                val hi = (center + PARTIAL_SEARCH_BINS).coerceAtMost(nBins - 1)
                if (lo <= hi) {
                    var peak = 0f; var peakBin = center
                    for (b in lo..hi) if (a.magnitudeSpectrum[b] > peak) { peak = a.magnitudeSpectrum[b]; peakBin = b }
                    if (peakBin in 0 until nBins) comb[peakBin] = peak
                }
                k++
            }
            return l2normalize(comb)
        }
    }
}

/** Fixed non-negative decomposition: explains [v] as `Σ aⱼ·Wⱼ` with aⱼ ≥ 0 (NMF multiplicative
 * update). Inputs should be L2-normalised. Returns one activation per column. A focused 2-candidate
 * {f/2, f} fit does not work (template(f/2) subsumes template(f)'s partials), so the resolver
 * decomposes over a full local octave; see DETECTION.md §12.6. */
fun nnls(v: FloatArray, columns: Array<FloatArray>, iterations: Int = 60): DoubleArray {
    val nCols = columns.size
    val nBins = v.size
    val a = DoubleArray(nCols) { 1.0 }
    val vhat = DoubleArray(nBins)
    repeat(iterations) {
        for (b in 0 until nBins) {
            var s = 0.0
            for (j in 0 until nCols) s += a[j] * columns[j][b]
            vhat[b] = s
        }
        for (j in 0 until nCols) {
            val wj = columns[j]; var num = 0.0; var den = 0.0
            for (b in 0 until nBins) { num += wj[b] * v[b]; den += wj[b] * vhat[b] }
            a[j] *= num / (den + 1e-9)
        }
    }
    return a
}

/** L2-normalise a vector to unit norm (no-op on the zero vector). */
fun l2normalize(v: FloatArray): FloatArray {
    var s = 0.0
    for (x in v) s += (x * x).toDouble()
    val n = sqrt(s).toFloat()
    return if (n <= 1e-12f) v.copyOf() else FloatArray(v.size) { v[it] / n }
}

/** SHELVED — resolves the octave of a detected pitch by decomposing the frame over a local octave
 * `[f/2, f]` (13 semitone candidates) and voting "sub-octave" when the strongest activation is the
 * bottom cluster, halving on a strict rolling majority. Conclusively defeated by the genuine-note /
 * octave-up spectral overlap (see the class KDoc above and DETECTION.md §12.6): a genuine La2 votes
 * sub-octave harder than a real Fa1→F2. Retained only for the guarded eval. */
class TemplateOctaveResolver(
    private val dictionary: HarmonicTemplateDictionary,
    private val lowVoteThreshold: Float,
    private val lowestPlayableHz: Float,
    private val missingFundamentalMaxHz: Float,
    private val aggregationWindow: Int = VOTE_WINDOW,
) {
    private val recentVotes = ArrayDeque<Boolean>() // true = this frame's best match is the sub-octave

    fun reset() = recentVotes.clear()

    fun resolve(amplitudeSpectrumSquared: FloatArray, df: Float, fHz: Float): Float {
        val half = fHz / 2f
        if (half < lowestPlayableHz || half > missingFundamentalMaxHz) {
            recentVotes.clear()
            return fHz
        }
        val nBins = (HarmonicTemplateDictionary.MAX_TEMPLATE_HZ / df).toInt()
            .coerceAtMost(amplitudeSpectrumSquared.size)
        val v = l2normalize(FloatArray(nBins) { sqrt(amplitudeSpectrumSquared[it].toDouble()).toFloat() })
        val cols = Array(SEMITONES + 1) { k ->
            dictionary.templateColumn(half * SEMITONE.toFloat().pow(k), df, nBins)
        }
        val a = nnls(v, cols)
        val winner = a.indices.maxByOrNull { a[it] }!!
        recentVotes.addLast(winner <= 2)
        while (recentVotes.size > aggregationWindow) recentVotes.removeFirst()

        val lowVotes = recentVotes.count { it }.toFloat() / recentVotes.size
        return if (lowVotes >= lowVoteThreshold) half else fHz
    }

    private companion object {
        const val SEMITONES = 12
        const val VOTE_WINDOW = 8
        val SEMITONE = 2.0.pow(1.0 / 12.0)
    }
}
