package be.drakarah.intonation.data

import kotlinx.serialization.decodeFromString
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json
import org.junit.Assert.assertEquals
import org.junit.Test

/** Guards the entity ↔ backup-DTO mapping (the most likely place a field is dropped) and that the
 * envelope survives a JSON round trip. Pure — no Room. */
class BackupDtoMappingTest {

    private val json = Json { encodeDefaults = true; ignoreUnknownKeys = true }

    private val session = SessionEntity(
        id = 7, startedAt = 1000, endedAt = 2000, exerciseType = "NOTE_ACCURACY", mode = "arco",
        configKey = "cfg", totalScore = 250, maxScore = 300, avgAbsCents = 12.5f, completed = true,
        epochDay = 20_100, contextJson = """{"a4Hz":440.0}""",
    )
    private val attempt = AttemptEntity(
        id = 3, sessionId = 7, promptIndex = 1, timestamp = 1000, exerciseType = "NOTE_ACCURACY",
        targetMidi = 40, targetFreqHz = 82.4f, startMidi = null, stringMidi = 28, positionId = "1st",
        playedFreqHz = 82.1f, centsError = -6.3f, reactionTimeMs = 1200, timeToStableMs = 800,
        score = 90, stars = 3, quality = "CLEAN", epochDay = 20_100, outcome = "SCORED",
        energyLevel = 77.5f, retryCount = 1, sustainHeldMs = null, sustainResets = null,
        steadinessCents = null, captureWobbleCents = 4.2f, extrasJson = null,
    )

    @Test fun attemptSurvivesEntityToDtoToEntity() {
        val restored = attempt.toBackup().toEntity(sessionId = 7)
        // id is autogenerated on insert, so compare everything except id.
        assertEquals(attempt.copy(id = 0), restored.copy(id = 0))
    }

    @Test fun sessionAndAttemptsSurviveJsonRoundTrip() {
        val envelope = BackupEnvelope(
            format = BACKUP_FORMAT, backupVersion = BACKUP_VERSION, dbSchemaVersion = 4,
            appVersionCode = 1, exportedAt = 123,
            data = BackupData(
                sessions = listOf(session.toBackup(listOf(attempt))),
                personalBests = listOf(BackupPersonalBest("cfg", 250, 300, 2000)),
                achievements = listOf(BackupAchievement("FIRST_ROUND", 1500)),
            ),
        )
        val restored = json.decodeFromString<BackupEnvelope>(json.encodeToString(envelope))
        assertEquals(envelope, restored)

        // And the nested session/attempt map back to entities intact.
        val s = restored.data.sessions.single()
        assertEquals(session.copy(id = 0), s.toEntity())
        // sessionId is intentionally dropped by the DTO (re-keyed on import), so normalize it.
        assertEquals(attempt.copy(id = 0, sessionId = 0), s.attempts.single().toEntity(sessionId = 0))
    }
}
